/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32g071xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Ouverture du GPIOA on passe le premier bit du RCC à 1 grâce à RCC_IOPENR_GPIOAEN
    RCC->IOPENR |= RCC_IOPENR_GPIOAEN;

    // LD4 (LED 4) -> PA5 (GPIOA5)

    // Effacer les deux bits liés à PA5
    GPIOA->MODER &= ~GPIO_MODER_MODE5;
    // Passer le premier bit PA5 à 1 pour configurer en sortie
    GPIOA->MODER |= GPIO_MODER_MODE5_0;
    // On configure la sortie PA5 à 1
    GPIOA->ODR |= GPIO_ODR_OD5;

    // SysTick = compteur.
    // Cela tourne à 16Mhz.
    // On initialise la valeur à partir de laquelle le compteur va démarrer.
    SysTick->LOAD = 16000000 - 1;
    // La valeur actuelle du compteur (pour réinitaliser le COUNTFLAG)
    SysTick->VAL = 0;
    // Configure et active le SysTick
    SysTick->CTRL = SysTick_CTRL_CLKSOURCE_Msk | SysTick_CTRL_ENABLE_Msk;

    /* Loop forever */
	for(;;){
		// SysTick_CTRL_COUNTFLAG_Msk paasse à 1 si SysTick arrive à zero
		if (SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk)
		{
			// XOR pour inverser le bit et passer la sortie PA5 à 1 ou 0 (eteindre ou allumer)
			GPIOA->ODR ^= GPIO_ODR_OD5;
		}
	}
}
