/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32g071xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "uart.h"
#include "stm32g071xx.h"
#include <string.h>

int main(void)
{
    uart_init();

    RCC->IOPENR |= RCC_IOPENR_GPIOAEN;

    // PA6 en sortie
    GPIOA->MODER &= ~GPIO_MODER_MODE6;
    GPIOA->MODER |= GPIO_MODER_MODE6_0;

    char command[16];

    while (1)
    {
        uart_receive_string(command, sizeof(command));

        if (strcmp(command, "MOTION") == 0)
        {
            GPIOA->ODR |= GPIO_ODR_OD6;
        }
        else if (strcmp(command, "CLEAR") == 0)
        {
            GPIOA->ODR &= ~GPIO_ODR_OD6;
        }
    }
}
